# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  body_size_limit: 15MB
  sample_limit: 5000
  target_limit: 30
  label_limit: 30
  label_name_length_limit: 250
  label_value_length_limit: 250
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']